### ISSUE TITLE
Not exactly sure the purpose?

### ISSUE THREAD

**Issue by realityexpander** [abeade/figma-import-plugin#8]
Im attempting to import my own figma file as a test, and its saying "No resource matches found!"

And i have a series of screens that are .PNG that I want to use as mock ups.

What am I missing here? 

It would be good to have a sample figma .zip file to show what the source figma file is supposed to look like.

Thank you.

**Comment by abeade** [comment]
Hello @realityexpander 

Sorry for the late response.

The plugin goal is to help adding resources downloaded from Figma to an Android project as drawables per density to be used in your app.

For example, in Figma you can export an image to PNG like this:

![image](https://github.com/abeade/figma-import-plugin/assets/19229476/7cf15da7-6c4b-4707-830e-211cf2ed5268)

When you click on the "Export" button in figma, you will get a ZIP file that can be used with the plugin:

![image](https://github.com/abeade/figma-import-plugin/assets/19229476/b3d58cc3-a92a-4975-bd14-03c33663f0d7)

As a result of the plugin execution the PNG resources will be placed in the drawable folder for each matched density:

![image](https://github.com/abeade/figma-import-plugin/assets/19229476/8ec69576-6384-4d56-b85a-7299befc9238)

I hope it helps

**Comment by realityexpander** [comment]
I had to abandon that strategy due to lack of response, thanks for the follow up even if it's been a year!

**Comment by abeade** [comment]
> I had to abandon that strategy due to lack of response, thanks for the follow up even if it's been a year!

Sorry about that 😅
